config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
        controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations',
          passwords: 'users/passwords',
          confirmations: 'users/confirmations'
        }

  get 'home', to: 'home#index'

  root to: 'home#index'

  resources :users do
    member do
      get 'restore'
    end

    collection do
      get 'deleted'
    end
  end

  resources :tickets do
    member do
      get 'restore'
      put 'update_status'
    end

    collection do
      get 'deleted'
    end
  end

  resources :departments do
    collection do
      get 'restore'
      get 'deleted'
    end
  end

  resources :issue_summaries do
    collection do
      get 'restore'
      get 'deleted'
    end
  end

  resources :users, only: [:index, :show, :destroy]
  resources :tickets, only: [:index, :new, :show, :destroy], :except => [ :create ] do
  post "create" => "tickets#create", :as => :create, :path => 'new', :on => :collection
end
  resources :posts, only: [:index, :new, :create]

  get "*path" => redirect("/404")

end

app/models/issue_summary.rb
class IssueSummary < ActiveRecord::Base
  has_many :tickets, :dependent => :destroy

  acts_as_paranoid

  validates :name, presence: true, length: { maximum: 20 }, on: [:create, :update]
  validate :unique_name, on: [:create, :update]

  def unique_name
    errors.add :name, 'has already been taken' if IssueSummary.with_deleted.where(name: self.name).exists? && self.changed? && self.name.downcase != self.name_was.try(:downcase)
  end
end

app/controllers/issue_summaries_controller.rb
class IssueSummariesController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource

  def index
    @issue_sums = IssueSummary.all
  end

  def new
    @issue_sum = IssueSummary.new
  end

  def create
    @issue_sum = IssueSummary.new(issue_summary_params)

    @issue_sum[:name] = @issue_sum[:name].strip

    respond_to do |format|
      if @issue_sum.valid? == false
       flash[:danger] = @issue_sum.errors.full_messages.to_sentence
       format.html { redirect_to new_issue_summary_path }
      else
        if @issue_sum.save
          flash[:success] = 'Issue Summary created successfully'
          format.html { redirect_to issue_summaries_path }
        else
          flash[:danger] = 'There is a problem in creating the Issue Summary'
          format.html { redirect_to new_issue_summary_path }
        end
      end
    end
  end

  def show
    @issue_sum = IssueSummary.find(params[:id])
  end

  def edit
    @issue_sum = IssueSummary.find(params[:id])
  end

  def update
    @issue_sum = IssueSummary.find(params[:id])

    params[:issue_summary][:name] = params[:issue_summary][:name].strip

    respond_to do |format|
      if @issue_sum.update_attributes(issue_summary_params)
        flash[:success] = "Issue Summary updated successfully"
        format.html { redirect_to @issue_sum }
      else
        flash.now[:danger] = @issue_sum.errors.full_messages.to_sentence
        format.html { render :edit }
      end
    end
  end

  def destroy
    @issue_sum = IssueSummary.find(params[:id])

    respond_to do |format|
      if @issue_sum.destroy
        flash[:success] = 'Issue Summary deleted successfully'
        format.html { redirect_to deleted_issue_summaries_path }
      else
        flash[:danger] = 'There is a problem in deleting the Issue Summary'
        format.html { redirect_to issue_summaries_path }
      end
    end
  end

  def deleted
    @issue_sums = IssueSummary.only_deleted
  end

  def restore
    respond_to do |format|
      if IssueSummary.restore(params[:resource_id])
        flash[:success] = 'Issue Summary restored successfully'
        format.html { redirect_to issue_summaries_path }
      else
        flash[:danger] = 'There is a problem in restoring the Issue Summary.'
        format.html { redirect_to issue_summaries_path }
      end
    end
  end

  private
  def issue_summary_params
    params.require(:issue_summary).permit(:name)
  end
end

app/helpers/issuesummaries_helper.rb
module IssuesummariesHelper
end

app/views/issue_summaries/deleted.html.haml
%h1 Deleted Issue Summaries
%br/

%table#myTable2.table.table-striped.table-bordered
  %thead
    %tr
      %th Issue Summary Id
      %th Name
      %th Deleted_At
      %th Action

  %tbody
    - @issue_sums.each do |issue_sum|
      %tr
        %td
          = issue_sum.id
        %td
          = issue_sum.name
        %td
          = issue_sum.deleted_at.in_time_zone("Asia/Kolkata").strftime("%d/%m/%Y")
        %td
          = link_to restore_issue_summaries_path(resource_id: issue_sum), class: "tag-tooltip", :data => {:toggle=>"tooltip"}, 'data-original-title' => "Restore", 'data-placement' => 'right' do
            %i.glyphicon.glyphicon-repeat

app/views/issue_summaries/edit.html.haml
%h1 Edit Issue Summary
%br

= form_for @issue_sum, url: {action: "update"}, html: { class: "clientside_validation" } do |f|
  .row
    .form-group
      .col-md-2
        = f.label :name
        = "*"
      .col-md-10
        = f.text_field :name, class: "form-control require_validation length_validation", maxlength: "20"
  .row
    .col-md-6
      .actions
        %br/
        = f.submit "Update", class: 'btn btn-primary'
        = link_to "Back", issue_summaries_path , class: 'btn btn-primary button', id: 'back-button'

app/views/issue_summaries/index.html.haml
%h1 Issue Summaries
%br/

%table#myTable2.table.table-striped.table-bordered
  %thead
    %tr
      %th Issue Summary Id
      %th Name
      %th Created_At
      %th Action

  %tbody
    - @issue_sums.each do |issue_sum|
      %tr
        %td
          = issue_sum.id
        %td
          = issue_sum.name
        %td
          = issue_sum.created_at.in_time_zone("Asia/Kolkata").strftime("%d/%m/%Y")
        %td
          = link_to issue_summary_path(issue_sum), class: "tag-tooltip", :data => {:toggle=>"tooltip"}, 'data-original-title' => "View", 'data-placement' => 'right' do
            %i.glyphicon.glyphicon-eye-open
          = link_to edit_issue_summary_path(issue_sum), class: "tag-tooltip", :data => {:toggle=>"tooltip"}, 'data-original-title' => "Edit", 'data-placement' => 'right' do
            %i.glyphicon.glyphicon-pencil
          = link_to issue_summary_path(issue_sum), class: "tag-tooltip", :data => {:toggle=>"tooltip"}, 'data-original-title' => "Delete", 'data-placement' => 'right', method: :delete, data: { confirm: ' Are you sure you want to delete this Issue Summary? All the tickets related to this issue summary will also be deleted !' } do
            %i.glyphicon.glyphicon-remove

app/views/issue_summaries/new.html.haml
%h1 New Issue Summary
%br

= form_for @issue_sum, url: issue_summaries_path, html: { class: "clientside_validation" } do |f|
  .row
    .form-group
      .col-md-2
        = f.label :name
        = "*"
      .col-md-10
        = f.text_field :name, class: "form-control require_validation length_validation", maxlength: "20"
  %br/
  .row
    .col-md-6
      .actions
        = f.submit "Create", class: 'btn btn-primary'
        = f.button "Reset", type: :reset, class: "btn btn-primary"
        = link_to "Back", issue_summaries_path , class: 'btn btn-primary button', id: 'back-button'

app/views/issue_summaries/show.html.haml
%h1 Issue Summary Show
%br
.row
  .col-md-3
    %strong Issue_sum Id
  .col-md-9
    = @issue_sum.id
%br/
.row
  .col-md-3
    %strong Name
  .col-md-9
    = @issue_sum.name

%br/
.row
  .col-md-3
    %strong Created At
  .col-md-9
    = @issue_sum.created_at.in_time_zone("Asia/Kolkata").strftime("%d/%m/%Y %H:%M %p")

%br/
= link_to "Back", issue_summaries_path, class: 'btn btn-primary button'