config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
        controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations',
          passwords: 'users/passwords',
          confirmations: 'users/confirmations'
        }

  get 'home', to: 'home#index'

  root to: 'home#index'

  resources :users do
    member do
      get 'restore'
    end

    collection do
      get 'deleted'
    end
  end

  resources :tickets do
    member do
      get 'restore'
      put 'update_status'
    end

    collection do
      get 'deleted'
    end
  end

  resources :departments do
    collection do
      get 'restore'
      get 'deleted'
    end
  end

  resources :issue_summaries do
    collection do
      get 'restore'
      get 'deleted'
    end
  end

  resources :users, only: [:index, :show, :destroy]
  resources :tickets, only: [:index, :new, :show, :destroy], :except => [ :create ] do
  post "create" => "tickets#create", :as => :create, :path => 'new', :on => :collection
end
  resources :posts, only: [:index, :new, :create]

  get "*path" => redirect("/404")

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :tickets, :dependent => :destroy

  acts_as_paranoid

  validates :name, presence: true, length: { maximum: 20 }, on: [:create, :update]
  validate :unique_name, on: [:create, :update]

  def unique_name
    errors.add :name, 'has already been taken' if Department.with_deleted.where(name: self.name).exists? && self.changed? && self.name.downcase != self.name_was.try(:downcase)
  end
end

app/controllers/departments_controller.rb
 class DepartmentsController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource

  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)

    @department[:name] = @department[:name].strip

    respond_to do |format|
      if @department.valid? == false
       flash.now[:danger] = @department.errors.full_messages.to_sentence
       format.html { render :new }
      else
        if @department.save
          flash[:success] = 'Department created successfully'
          format.html { redirect_to departments_path }
        else
          flash[:danger] = 'There is a problem in creating the department'
          format.html { render :new }
        end
      end
    end
  end

  def show
    @department = Department.find(params[:id])
  end

  def edit
    @department = Department.find(params[:id])
  end

  def update
    @department = Department.find(params[:id])

    params[:department][:name] = params[:department][:name].strip

    respond_to do |format|
      if @department.update_attributes(department_params)
        flash[:success] = "Department updated successfully"
        format.html { redirect_to @department }
      else
        flash.now[:danger] = @department.errors.full_messages.to_sentence
        format.html { render :edit }
      end
    end
  end

  def destroy
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.destroy
        flash[:success] = 'Department deleted successfully '
        format.html { redirect_to deleted_departments_path }
      else
        flash[:danger] = 'There is a problem in deleting the department.'
        format.html { redirect_to departments_path }
      end
    end
  end

  def deleted
    @departments = Department.only_deleted
  end

  def restore
    respond_to do |format|
      if Department.restore(params[:resource_id])
        flash[:success] = 'Department restored successfully'
        format.html { redirect_to departments_path }
      else
        flash[:danger] = 'There is a problem in restoring the department.'
        format.html { redirect_to departments_path }
      end
    end
  end

  private
  def department_params
    params.require(:department).permit(:name)
  end

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/deleted.html.haml
%h1 Deleted Departments
%br/

%table#myTable2.table.table-striped.table-bordered
  %thead
    %tr
      %th Department Id
      %th Name
      %th Deleted_At
      %th Action

  %tbody
    - @departments.each do |department|
      %tr
        %td
          = department.id
        %td
          = department.name
        %td
          = department.deleted_at.in_time_zone("Asia/Kolkata").strftime("%d/%m/%Y")
        %td
          = link_to restore_departments_path(resource_id: department), class: "tag-tooltip", :data => {:toggle=>"tooltip"}, 'data-original-title' => "Restore", 'data-placement' => 'right' do
            %i.glyphicon.glyphicon-repeat

app/views/departments/edit.html.haml
%h1 Edit Department
%br

= form_for @department, url: {action: "update"}, html: { class: "clientside_validation" } do |f|
  .row
    .form-group
      .col-md-2
        = f.label :name
        = "*"
      .col-md-10
        = f.text_field :name, class: "form-control require_validation length_validation", maxlength: "20"
  .row
    .col-md-6
      .actions
        %br/
        = f.submit "Update", class: 'btn btn-primary'
        = link_to "Back", departments_path , class: 'btn btn-primary button', id: 'back-button'

app/views/departments/index.html.haml
%h1 Departments
%br/

%table#myTable2.table.table-striped.table-bordered
  %thead
    %tr
      %th Department Id
      %th Name
      %th Created_At
      %th Action

  %tbody
    - @departments.each do |department|
      %tr
        %td
          = department.id
        %td
          = department.name
        %td
          = department.created_at.in_time_zone("Asia/Kolkata").strftime("%d/%m/%Y")
        %td
          = link_to department, class: "tag-tooltip", :data => {:toggle=>"tooltip"}, 'data-original-title' => "View", 'data-placement' => 'right' do
            %i.glyphicon.glyphicon-eye-open
          = link_to edit_department_path(department), class: "tag-tooltip", :data => {:toggle=>"tooltip"}, 'data-original-title' => "Edit", 'data-placement' => 'right' do
            %i.glyphicon.glyphicon-pencil
          = link_to department, class: "tag-tooltip", :data => {:toggle=>"tooltip"}, 'data-original-title' => "Delete", 'data-placement' => 'right', method: :delete, data: { confirm: ' Are you sure you want to delete this Department? All the tickets related to this department will also be deleted !' } do
            %i.glyphicon.glyphicon-remove

app/views/departments/new.html.haml
%h1 New Department
%br

= form_for @department, url: departments_path, html: { class: "clientside_validation" } do |f|
  .row
    .form-group
      .col-md-2
        = f.label :name
        = "*"
      .col-md-10
        = f.text_field :name, class: "form-control require_validation length_validation", maxlength: "20"
  %br/
  .row
    .col-md-6
      .actions
        = f.submit "Create", class: 'btn btn-primary'
        = f.button "Reset", type: :reset, class: "btn btn-primary"
        = link_to "Back", departments_path , class: 'btn btn-primary button', id: 'back-button'

app/views/departments/show.html.haml
%h1 Department Show
%br
.row
  .col-md-3
    %strong Department Id
  .col-md-9
    = @department.id
%br/
.row
  .col-md-3
    %strong Name
  .col-md-9
    = @department.name

%br/
.row
  .col-md-3
    %strong Created At
  .col-md-9
    = @department.created_at.in_time_zone("Asia/Kolkata").strftime("%d/%m/%Y %H:%M %p")

%br/
= link_to "Back", departments_path, class: 'btn btn-primary button'