config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
        controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations',
          passwords: 'users/passwords',
          confirmations: 'users/confirmations'
        }

  get 'home', to: 'home#index'

  root to: 'home#index'

  resources :users do
    member do
      get 'restore'
    end

    collection do
      get 'deleted'
    end
  end

  resources :tickets do
    member do
      get 'restore'
      put 'update_status'
    end

    collection do
      get 'deleted'
    end
  end

  resources :departments do
    collection do
      get 'restore'
      get 'deleted'
    end
  end

  resources :issue_summaries do
    collection do
      get 'restore'
      get 'deleted'
    end
  end

  resources :users, only: [:index, :show, :destroy]
  resources :tickets, only: [:index, :new, :show, :destroy], :except => [ :create ] do
  post "create" => "tickets#create", :as => :create, :path => 'new', :on => :collection
end
  resources :posts, only: [:index, :new, :create]

  get "*path" => redirect("/404")

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :department
  belongs_to :issue_summary, class_name: IssueSummary
  has_many :posts, :dependent => :destroy

  acts_as_paranoid

  has_attached_file :image

  resourcify

  sanitizes :issue_details, on: :create

  scope :filter_tickets_by_status, -> (status) {
    if User.current.has_role? :admin
      includes(:user,:department,:issue_summary).where(status: status).pluck(:id, "departments.name", "issue_summaries.name", :priority, :email, :location, :created_at).map { |e| [ e[0],e[1],e[2],e[3],e[4],e[5],e[6].strftime("%d/%m/%Y") ] }
    else
      includes(:user,:department,:issue_summary).where(status: status).pluck(:id, "departments.name", "issue_summaries.name", :priority, :created_at).map { |e| [ e[0],e[1],e[2],e[3],e[4].strftime("%d/%m/%Y") ] }
    end
  }
  scope :filter_deleted_tickets_by_status, -> (status) {
    if User.current.has_role? :admin
      includes(:user,:department,:issue_summary).where(status: status).pluck(:id, "departments.name", "issue_summaries.name" , :priority, :email, :deleted_at).map { |e| [ e[0],e[1],e[2],e[3],e[4],e[5].strftime("%d/%m/%Y") ] }
    else
      includes(:user,:department,:issue_summary).where(status: status).pluck(:id, "departments.name", "issue_summaries.name" , :priority, :deleted_at).map { |e| [ e[0],e[1],e[2],e[3],e[4].strftime("%d/%m/%Y") ] }
    end
  }

  validates :department, presence: true
  validates :issue_summary, presence: true
  validates :issue_details, presence: true, length: { maximum: 255 }
  validates :location, presence: true
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_size :image, :less_than => 5.megabytes

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource only: [:index, :new, :create, :show, :update_status, :destroy]

  def index
    if current_user.has_role? :admin
      @tickets = Ticket.all
    else
      @tickets = Ticket.where("user_id = ? ", current_user.id)
    end

    @final_tickets = @tickets.filter_tickets_by_status(params[:activetab])

    respond_to do |format|
      format.html
      format.json { render :json => {data: @final_tickets} }
    end
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params.merge(user_id: current_user.id, status: "Open"))

    respond_to do |format|
      if @ticket.valid? == false
        format.html { render :new }
      else
        if @ticket.save
          TicketMailer.ticket_email(@ticket).deliver
          flash[:success] = 'Ticket created successfully'
          format.html { redirect_to tickets_path }
        else
          flash[:danger] = 'There is a problem in creating the ticket'
          format.html { render :new }
        end
      end
    end
  end

  def show
    @ticket = Ticket.find(params[:id])

    @post = @ticket.posts.new

    @posts = @ticket.posts
  end

  def update_status
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_column(:status, params[:ticket][:status])
        flash[:success] = 'Status changed successfully'
        format.html { redirect_to tickets_path }
      else
        flash[:danger] = 'There is a problem in changing status'
        format.html { redirect_to ticket_path }
      end
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.destroy
        flash[:success] = 'Ticket deleted successfully'
        format.html { redirect_to tickets_path }
      else
        flash[:danger] = 'There is a problem in deleting the ticket.'
        format.html { redirect_to tickets_path }
      end
    end
  end

  def reload_page
    respond_to do |format|
      format.js {}
    end
  end

  def deleted
    if current_user.has_role? :admin
      @tickets = Ticket.only_deleted
    else
      @tickets = Ticket.only_deleted.where("user_id = ? ", current_user.id)
    end

    @final_tickets = @tickets.filter_deleted_tickets_by_status(params[:activetab])

    respond_to do |format|
      format.html
      format.json { render :json => {data: @final_tickets} }
    end
  end

  def restore
    @ticket = Ticket.only_deleted.find(params[:id])

    respond_to do |format|
      if Ticket.restore(@ticket.id)
        flash[:success] = 'Ticket restored successfully'
        format.html { redirect_to tickets_path }
      else
        flash[:danger] = 'There is a problem in restoring the ticket.'
        format.html { redirect_to tickets_path }
      end
    end
  end

  private
  def ticket_params
    params.require(:ticket).permit(:department_id,:issue_summary_id,:issue_details,:image,:priority,:location)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_nav_tabs.html.haml
%div
  %ul.nav.nav-tabs{:id => "#myTabs", :role => "tablist"}
    %li.active{:role => "presentation"}
      %a{"aria-controls" => "Open", "data-toggle" => "tab", "data-tab" => "Open", :href => "#open", :role => "tab"} Open
    %li{:role => "presentation"}
      %a{"aria-controls" => "Inprogress", "data-toggle" => "tab", "data-tab" => "In Progress", :href => "#inprogress", :role => "tab"} In Progress
    %li{:role => "presentation"}
      %a{"aria-controls" => "Completed", "data-toggle" => "tab", "data-tab" => "Completed", :href => "#completed", :role => "tab"} Completed

  #myTabContent.tab-content
    #open.tab-pane.fade.in.active{:role => "tabpanel"}
    #inprogress.tab-pane.fade{:role => "tabpanel"}
    #completed.tab-pane.fade{:role => "tabpanel"}

app/views/tickets/deleted.html.haml
%h1 Deleted Tickets
%br/

= render 'nav_tabs'

%br/

%table#myTable4.table.table-striped.table-bordered
  %thead
    %tr
      %th Ticket Id
      %th Department
      %th Issue Summary
      %th Priority
      -if current_user.has_role? :admin
        %th Created By
      %th Deleted_At
      %th Action

app/views/tickets/index.html.haml
%h1 Tickets
%br/

= render 'nav_tabs'

%br/

%table#myTable3.table.table-striped.table-bordered
  %thead
    %tr
      %th Ticket Id
      %th Department
      %th Issue Summary
      %th Priority
      -if current_user.has_role? :admin
        %th Created By
        %th Location
      %th Created_At
      %th Action

app/views/tickets/new.html.haml
%h1 Create a New Ticket
%p
  Please fill in the form below to open a new ticket.
%br/

= form_for @ticket, url: create_tickets_path , html: { class: "clientside_validation" } do |f|

  .row
    .col-md-2
      = f.label :department
      = "*"
    .col-md-10
      = f.collection_select :department_id, Department.all, :id, :name, {prompt: 'Select'} ,
      { class: "form-control require_validation", autofocus: true }

  .row
    .col-md-2
      = f.label :email
    .col-md-10
      = current_user.email
  .row
    .col-md-2
      = f.label :client
    .col-md-10
      = current_user.fullname.blank? ? "N/A" : current_user.fullname
  %br/
  .row
    .col-md-6
      %h4{:style => "color: #0000CD;"}
        Ticket Details
  .row
    .col-md-6
      %p
        Please Describe Your Issue
  %br/
  .row
    .col-md-2
      = f.label :issue_summary
      = "*"
    .col-md-10
      = f.collection_select :issue_summary_id, IssueSummary.all, :id, :name, {prompt: 'Select'} ,
      { class: "form-control require_validation"}
  .row
    .col-md-2
      = f.label :issue_details
      = "*"
  .row
    .col-md-10
      = f.text_area :issue_details, :class => "tinymce require_validation", :rows => 10, :cols => 60
  %br/
  .row
    .col-md-2
      =f.label :image
    .col-md-10
      = f.file_field :image, class: "file image_validation"
  %br/
  .row
    .col-md-2
      =f.label :priority
    .col-md-10
      = f.select :priority, [['Low','Low'],['Medium','Medium'],['High','High']], { :selected => 'Medium' }, { class: "form-control" }
  %br/
  .row
    .col-md-2
      = f.label :location
      = "*"
    .col-md-10
      = f.select :location, [['Ahemdabad','Ahemdabad'],['Gandhinagar','Gandhinagar'],['US Office','US Office']], {prompt: 'Select'}, { class: "form-control require_validation"}
  .row
    .col-md-2
      = f.label :Status
    .col-md-10
      Open
  .row
    .col-md-6
      .actions
        %br/
        = f.submit "Create", class: 'btn btn-primary'
        = f.button "Reset", type: :reset, class: "btn btn-primary"
        = link_to "Back", tickets_path , class: 'btn btn-primary button', id: 'back-button'
= tinymce

app/views/tickets/show.html.haml
%h1 Show a Ticket
= form_for @ticket, url: update_status_ticket_path(@ticket), method: :put do |f|
  .row
    .col-md-2
      %h5
        %strong Ticket No.
    .col-md-4
      %h5
        %strong
          = @ticket.id
  %br/
  .row
    .col-md-2
      -if current_user.has_role? :admin
        %strong Created By
      -else
        %strong Name
    .col-md-4
      -if current_user.has_role? :admin
        = @ticket.user.fullname.blank? ? @ticket.user.email : @ticket.user.fullname
      -else
        = @ticket.user.fullname.blank? ? "N/A" : @ticket.user.fullname
    .col-md-2
      %strong Department
    .col-md-4
      = @ticket.department.nil? ? "N/A" : @ticket.department.name
  %br/
  .row
    .col-md-2
      %strong Location
    .col-md-4
      = @ticket.location
    .col-md-2
      %strong Created At
    .col-md-4
      = @ticket.created_at.in_time_zone("Asia/Kolkata").strftime("%d/%m/%Y %H:%M %p")
  %br/
  .row
    .col-md-2
      %strong Issue Summary
    .col-md-4
      = @ticket.issue_summary.nil? ? "N/A" : @ticket.issue_summary.name
    .col-md-2
      %strong Priority
    .col-md-4
      = @ticket.priority
  %br/
  .row
    .col-md-2
      %strong Issue Details
    .col-md-4
      = @ticket.issue_details
    .col-md-2
      %strong File
    .col-md-4
      -if @ticket.image_file_name.nil?
        = "N/A"
      -else
        = link_to image_tag(@ticket.image.url, class: 'media-object', :style => "height: 50%; width: 100%;"), @ticket.image.url
  %br
  .row
    .col-md-2
      %strong Status
    .col-md-4
      - if current_user.has_role? :admin
        = f.select :status ,[['Open','Open'],['In progress','In Progress'],['Completed','Completed']]
        = f.submit "Update", class: 'btn btn-primary button'
      - else
        = @ticket.status

%br/
.row
  .col-md-12
    %strong All Posts
%br/
.row
  .col-md-12
    = render :partial => "posts/all_posts"

%br/
.row
  .col-md-10
    = render :partial => "posts/form"

= tinymce