config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
        controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations',
          passwords: 'users/passwords',
          confirmations: 'users/confirmations'
        }

  get 'home', to: 'home#index'

  root to: 'home#index'

  resources :users do
    member do
      get 'restore'
    end

    collection do
      get 'deleted'
    end
  end

  resources :tickets do
    member do
      get 'restore'
      put 'update_status'
    end

    collection do
      get 'deleted'
    end
  end

  resources :departments do
    collection do
      get 'restore'
      get 'deleted'
    end
  end

  resources :issue_summaries do
    collection do
      get 'restore'
      get 'deleted'
    end
  end

  resources :users, only: [:index, :show, :destroy]
  resources :tickets, only: [:index, :new, :show, :destroy], :except => [ :create ] do
  post "create" => "tickets#create", :as => :create, :path => 'new', :on => :collection
end
  resources :posts, only: [:index, :new, :create]

  get "*path" => redirect("/404")

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :ticket

  sanitizes :description, on: :create

  validates :description, presence: true, length: { maximum: 255 }, on: :create
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @ticket = Ticket.find(params[:post][:ticket_id])

    if params.permit!
      respond_to do |format|
        @post = @ticket.posts.new(params[:post])
        if @post.save
          flash[:success] = 'Post created successfully'
          format.html { redirect_to @ticket }
        else
          flash[:danger] = @post.errors.full_messages.to_sentence
          format.html { redirect_to ticket_path(@ticket) }
        end
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_all_posts.html.haml
- @posts.each_with_index do |ticket_post|
  - unless ticket_post.new_record?
    .row#post
      .row#post_title
        .col-md-6
          = ticket_post.created_at.in_time_zone("Asia/Kolkata").strftime("%d/%m/%Y %H:%M %p")
        .col-md-6
          - user = User.find(ticket_post.user_id)
          Posted By:
          = user.fullname.blank? ? user.email : user.fullname
      %br/
      .row#post_content
        .col-md-12
          = ticket_post.description
    %br/

app/views/posts/_form.html.haml
= form_for(@post) do |fp|

  = fp.label :Post
  = fp.text_area :description, :class => "tinymce", :rows => 8
  = fp.hidden_field :ticket_id, :value => @ticket.id
  = fp.hidden_field :user_id, :value => current_user.id

  %br/
  = fp.submit "Post", class: 'btn btn-primary'
  = fp.button "Reset", type: :reset, class: "btn btn-primary"
  = link_to "Back", tickets_path , class: 'btn btn-primary button', id: 'back-button'